version : "3.9"

services:
  eolo:
    build: .
    ports:
      - "3333:3333"
    volumes: 
      - .:/home/eolo
    command: "npm run dev"
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_PASSWORD=${USER_PASSWORD}
      - MYSQL_USER=${USER_db}
      - MYSQL_DATABASE=${DATABASE}
    ports: 
      - '3306:3306'
    volumes:
      - ./db_volume:/var/lib/mysql